version: "3.8"

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/goinfre/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/goinfre/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception

services:
#mariadb
  mariadb:
    image: mariadb:afatir
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
#nginx
  nginx:
    image: nginx:afatir
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:afatir
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
